target = ['vocals']
n_targets = 1
dataset = 'sourcefolder'
checkpoint_path = './checkpoints'
log_path = './Logs'
unidirectional = false
fmin = 110
qvar = 1.36
bins_per_octave = 72
hidden_size = 512
bandwidth = 16000
nb_channels = 2
nb_layers = 3
debug = false
quiet = false
seed = 42
use_wiener = false
wiener_len = 300
n_wiener_its = 1
wiener_softmax_init = false
compute_residual = true

train_config.epochs = 1000
train_config.train_data_percentage = 0.8
train_config.samples_per_track = 64
train_config.start_w_valid = false
train_config.train_batch_size = 18
train_config.num_train_workers = 14
train_config.lr = 0.00005
train_config.patience = 140
train_config.lr_decay_patience = 80
train_config.lr_decay_gamma = 0.3
train_config.weight_decay = 0.0000
train_config.seq_dur = 5
train_config.loss_fn = 'mse'
train_config.ccmse_mag_fact = 0.7
train_config.ccmse_phase_fact = 0.3
train_config.ccmse_gamma = 0.3

valid_config.valid_batch_size = 8
valid_config.fixed_seed = 1313
valid_config.samples_per_track = 16
valid_config.num_valid_workers = 8
valid_config.valid_seq_dur = 5